name: Build wheels

on:
  workflow_call:
  
jobs:
  buildwheels:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: install cibuildwheel
      run: python -m pip install cibuildwheel==2.16.5
    - name: build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD_VERBOSITY: 1
        CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
        CIBW_ARCHS_MACOS: "x86_64 arm64"
        CIBW_SKIP: "pp3*"
    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl
