name: Upload PyPI

on:
  workflow_call:

jobs:
  upload_pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tmtools 
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: wheelhouse/
      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages_dir: wheelhouse/
